# Site settings
title: Leif E. Hetland
url: https://example.github.io
description:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Leif E. Hetland

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: linkedin
    url: https://www.linkedin.com/in/leifehetland

  - title: twitter
    url: https://twitter.com/Glitchyphus

  - title: instagram
    url: https://www.instagram.com/glitchyphus/

  - title: github
    url: https://github.com/leifehetland

  
  


# Build settings
markdown: kramdown
permalink: pretty
